// lib/shop-data.ts
// Timeless Hadith — Premium Coin Shop Static Data
// 10 unique coins matching the design spec

import type { Product, Category, Review } from '@/types/shop';

export const CATEGORIES: Category[] = [
  {
    id: 'cat-01',
    slug: 'silver',
    title: 'Silver Coins',
    description: '1 oz fine silver — .999 purity. Legal tender from world mints.',
    image: { src: '/shop/categories/silver.jpg', alt: 'Silver collectible coins', width: 600, height: 600 },
    productCount: 5,
    featured: true,
  },
  {
    id: 'cat-02',
    slug: 'gold',
    title: 'Gold Coins',
    description: '1 oz fine gold — .9999 purity. American Eagle, Maple Leaf, and Krugerrand.',
    image: { src: '/shop/categories/gold.jpg', alt: 'Gold collectible coins', width: 600, height: 600 },
    productCount: 5,
    featured: true,
  },
];

export const BEST_SELLERS: Product[] = [
  // ─── Silver Coins ─────────────────────────────────────────────────────────────
  {
    id: 'prod-01',
    slug: 'canadian-silver-maple-leaf',
    title: 'Canadian Silver Maple Leaf',
    description: 'Struck by the Royal Canadian Mint. .9999 fine silver, 1 oz. The world\'s purest silver coin, featuring the iconic sugar maple leaf design on a radial line background.',
    price: 32.50,
    currency: 'USD',
    images: [
      { src: '/shop/coins/canadian-silver-maple-leaf.jpg', alt: 'Canadian Silver Maple Leaf coin — 1 oz .9999 fine silver', width: 800, height: 800 },
    ],
    category: 'Silver',
    categorySlug: 'silver',
    rating: 4.9,
    reviewCount: 312,
    badge: 'bestseller',
    tags: ['silver', 'Canada', 'maple leaf', '1oz', '.9999'],
    inStock: true,
    isDigital: false,
    freeShipping: false,
    sku: 'SIL-CML-001',
    metal: 'Silver',
    weight: '1 oz',
    purity: '.9999',
    year: 2024,
    mintage: 'Unlimited',
    condition: 'Brilliant Uncirculated',
  },
  {
    id: 'prod-02',
    slug: 'american-silver-eagle',
    title: 'American Silver Eagle',
    description: 'America\'s official silver bullion coin. Struck by the US Mint in .999 fine silver. Features Walking Liberty on the obverse and the heraldic eagle on the reverse.',
    price: 34.50,
    currency: 'USD',
    images: [
      { src: '/shop/coins/american-silver-eagle.jpg', alt: 'American Silver Eagle coin — 1 oz .999 fine silver', width: 800, height: 800 },
    ],
    category: 'Silver',
    categorySlug: 'silver',
    rating: 4.9,
    reviewCount: 428,
    badge: 'bestseller',
    tags: ['silver', 'USA', 'eagle', '1oz', '.999'],
    inStock: true,
    isDigital: false,
    freeShipping: false,
    sku: 'SIL-ASE-001',
    metal: 'Silver',
    weight: '1 oz',
    purity: '.999',
    year: 2024,
    mintage: 'Unlimited',
    condition: 'Brilliant Uncirculated',
  },
  {
    id: 'prod-03',
    slug: 'australian-silver-kookaburra',
    title: 'Australian Silver Kookaburra',
    description: 'From the Perth Mint — one of the most collected silver coin series in the world. Design changes annually. .9999 fine silver, 1 oz.',
    price: 32.00,
    currency: 'USD',
    images: [
      { src: '/shop/coins/australian-silver-kookaburra.jpg', alt: 'Australian Silver Kookaburra coin — 1 oz .9999 fine silver', width: 800, height: 800 },
    ],
    category: 'Silver',
    categorySlug: 'silver',
    rating: 4.8,
    reviewCount: 187,
    badge: 'new',
    tags: ['silver', 'Australia', 'kookaburra', '1oz', 'Perth Mint'],
    inStock: true,
    isDigital: false,
    freeShipping: false,
    sku: 'SIL-AKK-001',
    metal: 'Silver',
    weight: '1 oz',
    purity: '.9999',
    year: 2024,
    mintage: '500,000',
    condition: 'Brilliant Uncirculated',
  },
  {
    id: 'prod-04',
    slug: 'austrian-silver-philharmonic',
    title: 'Austrian Silver Philharmonic',
    description: 'Europe\'s best-selling silver coin. Struck by the Austrian Mint since 2008. Features the Great Organ of the Vienna Philharmonic concert hall. .999 fine silver.',
    price: 33.00,
    currency: 'USD',
    images: [
      { src: '/shop/coins/austrian-silver-philharmonic.jpg', alt: 'Austrian Silver Philharmonic coin — 1 oz .999 fine silver', width: 800, height: 800 },
    ],
    category: 'Silver',
    categorySlug: 'silver',
    rating: 4.7,
    reviewCount: 143,
    tags: ['silver', 'Austria', 'philharmonic', '1oz', '.999'],
    inStock: true,
    isDigital: false,
    freeShipping: false,
    sku: 'SIL-AVP-001',
    metal: 'Silver',
    weight: '1 oz',
    purity: '.999',
    year: 2024,
    mintage: 'Unlimited',
    condition: 'Brilliant Uncirculated',
  },
  {
    id: 'prod-05',
    slug: 'mjolnir-hammer-silver',
    title: 'Mjolnir Hammer — Antique Finish',
    description: 'A rare antiqued silver round depicting Thor\'s hammer, Mjolnir. Hand-finished with careful antiquing to highlight every detail. .999 fine silver, 1 oz. Limited to 5,000 pieces.',
    price: 89.00,
    originalPrice: 99.00,
    currency: 'USD',
    images: [
      { src: '/shop/coins/mjolnir-hammer.jpg', alt: 'Mjolnir Thor hammer antique silver coin 1oz', width: 800, height: 800 },
    ],
    category: 'Silver',
    categorySlug: 'silver',
    rating: 5.0,
    reviewCount: 64,
    badge: 'limited',
    tags: ['silver', 'Mjolnir', 'Thor', 'antique', 'limited edition'],
    inStock: true,
    isDigital: false,
    freeShipping: true,
    sku: 'SIL-MJH-001',
    metal: 'Silver',
    weight: '1 oz',
    purity: '.999',
    year: 2024,
    mintage: '5,000',
    condition: 'Antique Finish',
  },
  // ─── Gold Coins ───────────────────────────────────────────────────────────────
  {
    id: 'prod-06',
    slug: 'american-gold-eagle',
    title: 'American Gold Eagle',
    description: 'The flagship US gold coin — struck in 22-karat gold with .9167 fine gold content. Walking Liberty design by Augustus Saint-Gaudens. Legal tender, $50 face value.',
    price: 1950.00,
    currency: 'USD',
    images: [
      { src: '/shop/coins/american-gold-eagle.jpg', alt: 'American Gold Eagle coin — 1 oz 22k gold', width: 800, height: 800 },
    ],
    category: 'Gold',
    categorySlug: 'gold',
    rating: 4.9,
    reviewCount: 97,
    badge: 'bestseller',
    tags: ['gold', 'USA', 'eagle', '1oz', '22k'],
    inStock: true,
    isDigital: false,
    freeShipping: true,
    sku: 'GLD-AGE-001',
    metal: 'Gold',
    weight: '1 oz',
    purity: '.9167 (22k)',
    year: 2024,
    mintage: 'Unlimited',
    condition: 'Brilliant Uncirculated',
  },
  {
    id: 'prod-07',
    slug: 'canadian-gold-maple-leaf',
    title: 'Canadian Gold Maple Leaf',
    description: 'The world\'s first .9999 fine gold coin. Struck by the Royal Canadian Mint since 1979. The gold standard of purity — 99.99% gold, guaranteed by the Canadian government.',
    price: 1980.00,
    currency: 'USD',
    images: [
      { src: '/shop/coins/canadian-gold-maple-leaf.jpg', alt: 'Canadian Gold Maple Leaf coin — 1 oz .9999 fine gold', width: 800, height: 800 },
    ],
    category: 'Gold',
    categorySlug: 'gold',
    rating: 4.9,
    reviewCount: 134,
    badge: 'bestseller',
    tags: ['gold', 'Canada', 'maple leaf', '1oz', '.9999'],
    inStock: true,
    isDigital: false,
    freeShipping: true,
    sku: 'GLD-CML-001',
    metal: 'Gold',
    weight: '1 oz',
    purity: '.9999',
    year: 2024,
    mintage: 'Unlimited',
    condition: 'Brilliant Uncirculated',
  },
  {
    id: 'prod-08',
    slug: 'south-african-krugerrand',
    title: 'South African Krugerrand',
    description: 'The world\'s first modern gold bullion coin, minted since 1967. 22-karat gold, 1 oz fine gold content. The Krugerrand is the most widely traded gold coin on earth.',
    price: 1975.00,
    currency: 'USD',
    images: [
      { src: '/shop/coins/south-african-krugerrand.jpg', alt: 'South African Krugerrand gold coin — 1 oz 22k gold', width: 800, height: 800 },
    ],
    category: 'Gold',
    categorySlug: 'gold',
    rating: 4.8,
    reviewCount: 211,
    tags: ['gold', 'South Africa', 'Krugerrand', '1oz', '22k'],
    inStock: true,
    isDigital: false,
    freeShipping: true,
    sku: 'GLD-KRG-001',
    metal: 'Gold',
    weight: '1 oz',
    purity: '.9167 (22k)',
    year: 2024,
    mintage: 'Unlimited',
    condition: 'Brilliant Uncirculated',
  },
  {
    id: 'prod-09',
    slug: 'chinese-gold-panda',
    title: 'Chinese Gold Panda',
    description: 'China\'s beloved collectible gold coin, featuring a new panda design each year. .999 fine gold. Struck by the China Mint — one of the world\'s most collected coin series.',
    price: 1965.00,
    currency: 'USD',
    images: [
      { src: '/shop/coins/chinese-gold-panda.jpg', alt: 'Chinese Gold Panda coin — 1 oz .999 fine gold', width: 800, height: 800 },
    ],
    category: 'Gold',
    categorySlug: 'gold',
    rating: 4.8,
    reviewCount: 88,
    badge: 'new',
    tags: ['gold', 'China', 'panda', '1oz', '.999'],
    inStock: true,
    isDigital: false,
    freeShipping: true,
    sku: 'GLD-CGP-001',
    metal: 'Gold',
    weight: '1 oz',
    purity: '.999',
    year: 2024,
    mintage: '600,000',
    condition: 'Brilliant Uncirculated',
  },
  {
    id: 'prod-10',
    slug: 'american-gold-buffalo',
    title: 'American Gold Buffalo',
    description: 'America\'s first .9999 fine gold coin. The design is based on James Earle Fraser\'s iconic 1913 Buffalo Nickel. Struck by the US Mint — legal tender, $50 face value.',
    price: 1980.00,
    currency: 'USD',
    images: [
      { src: '/shop/coins/american-gold-buffalo.jpg', alt: 'American Gold Buffalo coin — 1 oz .9999 fine gold', width: 800, height: 800 },
    ],
    category: 'Gold',
    categorySlug: 'gold',
    rating: 4.9,
    reviewCount: 156,
    badge: 'bestseller',
    tags: ['gold', 'USA', 'buffalo', '1oz', '.9999'],
    inStock: true,
    isDigital: false,
    freeShipping: true,
    sku: 'GLD-AGB-001',
    metal: 'Gold',
    weight: '1 oz',
    purity: '.9999',
    year: 2024,
    mintage: 'Unlimited',
    condition: 'Brilliant Uncirculated',
  },
];

export const REVIEWS: Review[] = [
  {
    id: 'rev-01',
    authorName: 'Michael T.',
    authorLocation: 'Dallas, TX',
    rating: 5,
    title: 'Stunning quality — arrived perfectly',
    body: 'The Mjolnir round is even more impressive in person. The antique finish brings out every detail beautifully. Arrived in a capsule with a COA. Will definitely order again.',
    date: '2026-03-14',
    verified: true,
    productId: 'prod-05',
    productTitle: 'Mjolnir Hammer — Antique Finish',
  },
  {
    id: 'rev-02',
    authorName: 'Sarah K.',
    authorLocation: 'Vancouver, BC',
    rating: 5,
    title: 'Best silver I have bought online',
    body: 'Canadian Maple Leaf arrived in perfect condition, same day shipping, tracking worked great. The coin is flawless. This is my fourth order from Timeless and I trust them completely.',
    date: '2026-02-28',
    verified: true,
    productId: 'prod-01',
    productTitle: 'Canadian Silver Maple Leaf',
  },
  {
    id: 'rev-03',
    authorName: 'James R.',
    authorLocation: 'London, UK',
    rating: 5,
    title: 'Gold Buffalo exceeded expectations',
    body: 'Ordered the Gold Buffalo after comparing several dealers. Price was competitive and it arrived in a beautiful presentation box with all documentation. Spot-on .9999 purity.',
    date: '2026-03-02',
    verified: true,
    productId: 'prod-10',
    productTitle: 'American Gold Buffalo',
  },
  {
    id: 'rev-04',
    authorName: 'Ahmed F.',
    authorLocation: 'Dubai, UAE',
    rating: 5,
    title: 'International shipping was fast',
    body: 'Ordered three Silver Eagles from Dubai. They arrived in 6 business days, fully insured. Packaging was top-notch — each coin in its own capsule inside a padded box. Very professional.',
    date: '2026-01-19',
    verified: true,
    productId: 'prod-02',
    productTitle: 'American Silver Eagle',
  },
];

export const SHOP_FAQ = [
  {
    question: 'Do you ship internationally?',
    answer: 'Yes — we ship to over 80 countries, fully insured. Digital products are delivered instantly by email. Orders over $200 ship free.',
  },
  {
    question: 'Are your coins authentic?',
    answer: 'Every coin is 100% genuine, sourced directly from authorised mint distributors. Each coin ships with its original capsule and certificate of authenticity where applicable.',
  },
  {
    question: 'What is your return policy?',
    answer: 'We offer a 30-day return policy on all coins in original, unopened condition. Return shipping is the buyer\'s responsibility unless the item arrived damaged.',
  },
  {
    question: 'How do you handle pricing?',
    answer: 'Our prices are updated daily based on live spot prices. The price you see at checkout is locked in for 15 minutes. After that, the cart refreshes to the current rate.',
  },
];
