// lib/shop-data.ts
// Timeless Hadith — Static Shop Data
// Replace image src values with your actual CDN/asset paths

import type { Product, Category, Review } from '@/types/shop';

export const CATEGORIES: Category[] = [
  {
    id: 'cat-01',
    slug: 'wall-art',
    title: 'Wall Art',
    description: 'Quranic verses and Islamic geometric art, museum-quality printed.',
    image: { src: '/shop/categories/wall-art.jpg', alt: 'Islamic calligraphy wall art', width: 600, height: 800 },
    productCount: 48,
    featured: true,
  },
  {
    id: 'cat-02',
    slug: 'journals',
    title: 'Journals',
    description: 'Guided reflection journals, Quran reading trackers, and gratitude books.',
    image: { src: '/shop/categories/journals.jpg', alt: 'Premium Islamic journals', width: 600, height: 800 },
    productCount: 22,
    featured: true,
  },
  {
    id: 'cat-03',
    slug: 'prayer-essentials',
    title: 'Prayer Essentials',
    description: 'Prayer mats, tasbeeh, Qibla compasses, and prayer time accessories.',
    image: { src: '/shop/categories/prayer-essentials.jpg', alt: 'Islamic prayer essentials', width: 600, height: 800 },
    productCount: 36,
    featured: true,
  },
  {
    id: 'cat-04',
    slug: 'books',
    title: 'Books',
    description: 'Curated collection of Islamic literature, Hadith collections, and scholarship.',
    image: { src: '/shop/categories/books.jpg', alt: 'Islamic books collection', width: 600, height: 800 },
    productCount: 64,
    featured: true,
  },
  {
    id: 'cat-05',
    slug: 'apparel',
    title: 'Apparel',
    description: 'Minimal, modest, and meaningful — clothing that speaks without shouting.',
    image: { src: '/shop/categories/apparel.jpg', alt: 'Modest Islamic apparel', width: 600, height: 800 },
    productCount: 30,
    featured: true,
  },
  {
    id: 'cat-06',
    slug: 'kids-learning',
    title: 'Kids Learning',
    description: 'Engaging Islamic education tools for young minds — beautifully designed.',
    image: { src: '/shop/categories/kids-learning.jpg', alt: 'Islamic learning tools for kids', width: 600, height: 800 },
    productCount: 18,
    featured: false,
  },
  {
    id: 'cat-07',
    slug: 'home-decor',
    title: 'Home Decor',
    description: 'Transform your living space with meaningful Islamic accents.',
    image: { src: '/shop/categories/home-decor.jpg', alt: 'Islamic home decor', width: 600, height: 800 },
    productCount: 42,
    featured: false,
  },
  {
    id: 'cat-08',
    slug: 'digital-products',
    title: 'Digital Products',
    description: 'Printable planners, digital journals, and instant-access Islamic resources.',
    image: { src: '/shop/categories/digital-products.jpg', alt: 'Islamic digital products', width: 600, height: 800 },
    productCount: 26,
    featured: false,
  },
];

export const BEST_SELLERS: Product[] = [
  {
    id: 'prod-01',
    slug: 'ayat-al-kursi-framed-art',
    title: 'Ayat Al-Kursi — Framed Art Print',
    description: 'Archival-quality giclée print of Ayat Al-Kursi in classical Thuluth calligraphy. Arrives ready to hang.',
    price: 89,
    currency: 'USD',
    images: [
      { src: '/shop/products/ayat-al-kursi.jpg', alt: 'Ayat Al-Kursi framed calligraphy art', width: 800, height: 800 },
    ],
    category: 'Wall Art',
    categorySlug: 'wall-art',
    rating: 4.9,
    reviewCount: 347,
    badge: 'bestseller',
    tags: ['Quran', 'calligraphy', 'wall art', 'gift', 'Islamic gifts'],
    inStock: true,
    isDigital: false,
    freeShipping: true,
    sku: 'WA-AK-001',
  },
  {
    id: 'prod-02',
    slug: 'ramadan-reflection-journal',
    title: 'Ramadan Reflection Journal',
    description: '30-day guided journal for Ramadan — daily Quran reflections, dua tracking, and spiritual goals.',
    price: 34,
    originalPrice: 42,
    currency: 'USD',
    images: [
      { src: '/shop/products/ramadan-journal.jpg', alt: 'Ramadan reflection journal', width: 800, height: 800 },
    ],
    category: 'Journals',
    categorySlug: 'journals',
    rating: 4.8,
    reviewCount: 212,
    badge: 'ramadan',
    tags: ['Ramadan', 'journal', 'Islamic gifts', 'reflection', 'dua'],
    inStock: true,
    isDigital: false,
    freeShipping: false,
    sku: 'JR-RR-001',
  },
  {
    id: 'prod-03',
    slug: 'premium-prayer-mat-geometric',
    title: 'Heritage Prayer Mat — Geometric Collection',
    description: 'Hand-tufted 100% wool prayer mat with authentic Islamic geometric motifs. Non-slip backing.',
    price: 129,
    currency: 'USD',
    images: [
      { src: '/shop/products/prayer-mat.jpg', alt: 'Premium Islamic prayer mat geometric design', width: 800, height: 800 },
    ],
    category: 'Prayer Essentials',
    categorySlug: 'prayer-essentials',
    rating: 4.9,
    reviewCount: 189,
    badge: 'bestseller',
    tags: ['prayer mat', 'Islamic gifts', 'prayer essentials', 'Eid gifts', 'Muslim merchandise'],
    inStock: true,
    isDigital: false,
    freeShipping: true,
    sku: 'PE-PM-002',
  },
  {
    id: 'prod-04',
    slug: 'riyad-as-salihin-premium-edition',
    title: 'Riyad As-Salihin — Premium Leather Edition',
    description: 'Full English translation with Arabic text, premium leather binding, gold-leaf edges.',
    price: 68,
    currency: 'USD',
    images: [
      { src: '/shop/products/riyad-salihin.jpg', alt: 'Riyad As-Salihin premium leather book', width: 800, height: 800 },
    ],
    category: 'Books',
    categorySlug: 'books',
    rating: 4.7,
    reviewCount: 94,
    badge: 'new',
    tags: ['Hadith', 'books', 'Islamic books', 'Muslim gifts', 'premium'],
    inStock: true,
    isDigital: false,
    freeShipping: false,
    sku: 'BK-RS-001',
  },
  {
    id: 'prod-05',
    slug: 'bismillah-minimal-tshirt',
    title: 'Bismillah — Minimal Tee',
    description: 'Brushed 100% organic cotton. Bismi\'llah in refined Nastaliq script. Unisex, pre-shrunk, ethically made.',
    price: 45,
    currency: 'USD',
    images: [
      { src: '/shop/products/bismillah-tee.jpg', alt: 'Bismillah minimal Islamic t-shirt', width: 800, height: 800 },
    ],
    category: 'Apparel',
    categorySlug: 'apparel',
    rating: 4.6,
    reviewCount: 143,
    badge: 'new',
    tags: ['Islamic apparel', 'Muslim merchandise', 'modest fashion', 'Islamic clothing'],
    inStock: true,
    isDigital: false,
    freeShipping: false,
    sku: 'AP-BT-001',
  },
  {
    id: 'prod-06',
    slug: 'eid-gift-bundle',
    title: 'Eid Gift Bundle — The Complete Set',
    description: 'Curated Eid gift set: framed art, journal, premium dates, and hand-written card. Gift-wrapped.',
    price: 149,
    originalPrice: 198,
    currency: 'USD',
    images: [
      { src: '/shop/products/eid-bundle.jpg', alt: 'Premium Eid gift bundle set', width: 800, height: 800 },
    ],
    category: 'Gifts',
    categorySlug: 'gifts',
    rating: 5.0,
    reviewCount: 67,
    badge: 'limited',
    tags: ['Eid gifts', 'gift bundle', 'Islamic gifts', 'Ramadan gifts', 'Muslim gifts'],
    inStock: true,
    isDigital: false,
    freeShipping: true,
    sku: 'GF-EB-001',
  },
  {
    id: 'prod-07',
    slug: 'arabic-alphabet-kids-flashcards',
    title: 'Arabic Alphabet — Kids Flashcard Set',
    description: '28 illustrated, double-sided flashcards. Each letter paired with a relatable word and image.',
    price: 28,
    currency: 'USD',
    images: [
      { src: '/shop/products/kids-flashcards.jpg', alt: 'Arabic alphabet kids flashcards', width: 800, height: 800 },
    ],
    category: 'Kids Learning',
    categorySlug: 'kids-learning',
    rating: 4.8,
    reviewCount: 228,
    badge: 'bestseller',
    tags: ['kids learning', 'Arabic alphabet', 'Islamic education', 'children', 'Muslim kids'],
    inStock: true,
    isDigital: false,
    freeShipping: false,
    sku: 'KL-AF-001',
  },
  {
    id: 'prod-08',
    slug: 'ramadan-planner-digital',
    title: 'Ramadan Planner — Digital Download',
    description: 'Printable 30-page PDF planner. Suhoor and Iftar schedule, prayer tracker, Quran goals. Instant access.',
    price: 12,
    currency: 'USD',
    images: [
      { src: '/shop/products/digital-planner.jpg', alt: 'Digital Ramadan planner download', width: 800, height: 800 },
    ],
    category: 'Digital Products',
    categorySlug: 'digital-products',
    rating: 4.7,
    reviewCount: 381,
    badge: 'bestseller',
    tags: ['digital products', 'Ramadan planner', 'printable', 'Islamic planner', 'instant download'],
    inStock: true,
    isDigital: true,
    freeShipping: true,
    sku: 'DP-RP-001',
  },
];

export const REVIEWS: Review[] = [
  {
    id: 'rev-01',
    authorName: 'Fatima A.',
    authorLocation: 'London, UK',
    rating: 5,
    title: 'The most beautiful purchase I have made all year.',
    body: 'The Ayat Al-Kursi print arrived perfectly packaged. The quality of the print, the frame, the paper — everything is truly premium. It is hanging in my living room and every guest who visits asks about it.',
    date: '2025-12-18',
    verified: true,
    productId: 'prod-01',
    productTitle: 'Ayat Al-Kursi — Framed Art Print',
  },
  {
    id: 'rev-02',
    authorName: 'Ibrahim K.',
    authorLocation: 'Toronto, Canada',
    rating: 5,
    title: 'Changed how I approach Ramadan completely.',
    body: 'I used this journal every single day of Ramadan. The prompts are thoughtful, not generic. You can tell this was designed by someone who actually understands what a Muslim wants to reflect on during this month.',
    date: '2026-01-03',
    verified: true,
    productId: 'prod-02',
    productTitle: 'Ramadan Reflection Journal',
  },
  {
    id: 'rev-03',
    authorName: 'Aisha M.',
    authorLocation: 'Dubai, UAE',
    rating: 5,
    title: 'Prayer mat of dreams. Worth every dirham.',
    body: 'I searched for a quality prayer mat for years. This one is thick, the geometric pattern is stunning, and it has not moved an inch on my marble floor. Worth every penny and then some.',
    date: '2025-11-29',
    verified: true,
    productId: 'prod-03',
    productTitle: 'Heritage Prayer Mat — Geometric Collection',
  },
  {
    id: 'rev-04',
    authorName: 'Yusuf T.',
    authorLocation: 'Kuala Lumpur, MY',
    rating: 5,
    title: 'The Eid bundle was the best gift I have ever given.',
    body: 'My mother cried when she opened it. Everything was wrapped beautifully with a handwritten card. The framed art, the journal — she uses them every day. Will be ordering again for every Eid.',
    date: '2026-02-14',
    verified: true,
    productId: 'prod-06',
    productTitle: 'Eid Gift Bundle — The Complete Set',
  },
];

export const SHOP_FAQ = [
  {
    question: 'Do you ship internationally?',
    answer: 'Yes — we ship to over 80 countries. Shipping times and costs vary by region. Digital products are delivered instantly by email.',
  },
  {
    question: 'Are your products ethically made?',
    answer: 'Every physical product is sourced from ethical suppliers with fair-labor standards. We audit our supply chain annually.',
  },
  {
    question: 'What is your return policy?',
    answer: 'We offer a 30-day no-questions-asked return policy on all physical products in original condition. Digital downloads are non-refundable once accessed.',
  },
  {
    question: 'How do I receive digital products?',
    answer: 'After checkout, you receive an email with a secure download link. Files are available for 7 days and can be downloaded up to 5 times.',
  },
];
