import type { Hadith } from "@/src/lib/hadith/types";

function summarize(query: string, items: Hadith[]): string {
  if (!items.length) {
    return `We couldn't find hadith matching "${query}". Try a different keyword, an Arabic root word, or the narrator's name.`;
  }
  const first = items[0];
  const collections = Array.from(new Set(items.slice(0, 5).map((h) => h.collection))).join(", ");
  const snippet = first.english ? first.english.slice(0, 160) : first.summary || "";
  return `Searches for "${query}" surface ${items.length} relevant hadith across ${collections}. ` +
    (snippet ? `One representative narration begins: "${snippet}${snippet.length === 160 ? "…" : ""}"` : "") +
    ` These results are grouped from text matches in the source corpus, not generated by an AI model.`;
}

export default function AISummaryBox({ query, items }: { query: string; items: Hadith[] }) {
  return (
    <section className="reader-card p-5 sm:p-6 mb-5">
      <header className="flex items-center gap-2 text-sm font-semibold text-[var(--reader-ink)] dark:text-white">
        <svg viewBox="0 0 24 24" width="16" height="16" className="text-[var(--reader-green)]" fill="currentColor">
          <path d="M12 2 L14 9 L21 9 L15.5 13 L17.5 20 L12 16 L6.5 20 L8.5 13 L3 9 L10 9 Z" />
        </svg>
        Generated from search results
      </header>
      <p className="mt-2 text-sm text-black/70 dark:text-white/75 leading-relaxed">
        {summarize(query, items)}
      </p>
      <p className="mt-3 text-[11px] text-black/45 dark:text-white/45">
        Grounded in {items.length} source result{items.length === 1 ? "" : "s"} · No AI model invoked.
      </p>
    </section>
  );
}
