-- =============================================================================
-- Migration: 001_hadith_progress_dashboard.sql
-- Project:   Timeless Hadith
-- Purpose:   Add user progress, dashboard, leaderboard, and achievement tracking
--            on top of the existing public.hadiths table.
--
-- SAFETY CONTRACT
--   * Additive only — nothing is dropped or renamed.
--   * public.hadiths is NOT modified.
--   * No foreign key from hadith_progress.hadith_id to public.hadiths.id
--     (intentional — keeps reimports of hadith content non-destructive).
--   * Auth schema is NOT modified.
--   * Every user-owned table has RLS enabled and self-only write policies.
--   * Public hadith content remains readable by anon (existing behavior).
--   * The mark_hadith_as_read RPC ignores any client-supplied user id and
--     binds to auth.uid() inside the function. SECURITY DEFINER, search_path
--     pinned to public, pg_temp. Auth gate checks BOTH auth.uid() IS NOT NULL
--     and auth.role() = 'authenticated'.
--   * user_achievements is read-only to clients. No INSERT/UPDATE/DELETE
--     policies exist on the table — achievements can ONLY be unlocked by
--     the mark_hadith_as_read RPC (SECURITY DEFINER bypasses RLS).
--   * mark_hadith_as_read normalises p_source to one of:
--       reader | category | dashboard | competition | import
--     Anything else collapses to 'reader'.
--
-- USAGE
--   Run from Supabase SQL Editor as a single transaction.
--   Re-running is safe: every CREATE uses IF NOT EXISTS / OR REPLACE,
--   every policy uses DROP POLICY IF EXISTS before CREATE POLICY,
--   seed inserts use ON CONFLICT DO NOTHING.
-- =============================================================================

BEGIN;

-- =============================================================================
-- 0. Helper: shared updated_at trigger function
-- =============================================================================
CREATE OR REPLACE FUNCTION public.tg_set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

COMMENT ON FUNCTION public.tg_set_updated_at IS
  'Generic trigger: stamps updated_at = now() on row update.';


-- =============================================================================
-- 1. user_profiles
--    One row per Supabase auth user. Display fields used by leaderboards.
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.user_profiles (
  id            uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  display_name  text,
  avatar_url    text,
  company       text,
  country       text,
  timezone      text NOT NULL DEFAULT 'UTC',
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.user_profiles IS
  'Per-user profile fields. id mirrors auth.users.id with CASCADE delete.';

DROP TRIGGER IF EXISTS trg_user_profiles_updated_at ON public.user_profiles;
CREATE TRIGGER trg_user_profiles_updated_at
  BEFORE UPDATE ON public.user_profiles
  FOR EACH ROW EXECUTE FUNCTION public.tg_set_updated_at();

ALTER TABLE public.user_profiles ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "user_profiles_authenticated_read" ON public.user_profiles;
CREATE POLICY "user_profiles_authenticated_read"
  ON public.user_profiles FOR SELECT
  TO authenticated
  USING (true);

DROP POLICY IF EXISTS "user_profiles_self_insert" ON public.user_profiles;
CREATE POLICY "user_profiles_self_insert"
  ON public.user_profiles FOR INSERT
  TO authenticated
  WITH CHECK (id = auth.uid());

DROP POLICY IF EXISTS "user_profiles_self_update" ON public.user_profiles;
CREATE POLICY "user_profiles_self_update"
  ON public.user_profiles FOR UPDATE
  TO authenticated
  USING (id = auth.uid())
  WITH CHECK (id = auth.uid());

DROP POLICY IF EXISTS "user_profiles_self_delete" ON public.user_profiles;
CREATE POLICY "user_profiles_self_delete"
  ON public.user_profiles FOR DELETE
  TO authenticated
  USING (id = auth.uid());


-- =============================================================================
-- 2. hadith_progress
--    Per-user mark-as-read log. hadith_id is bigint (matches hadiths.id).
--    NO foreign key to public.hadiths — see SAFETY CONTRACT.
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.hadith_progress (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     uuid   NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  hadith_id   bigint NOT NULL,
  source      text   NOT NULL DEFAULT 'reader',
  read_at     timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT  hadith_progress_user_hadith_unique UNIQUE (user_id, hadith_id)
);

COMMENT ON TABLE public.hadith_progress IS
  'Per-user mark-as-read entries. UNIQUE(user_id, hadith_id) prevents dupes.';
COMMENT ON COLUMN public.hadith_progress.hadith_id IS
  'References public.hadiths.id (bigint). No FK — see migration safety contract.';
COMMENT ON COLUMN public.hadith_progress.source IS
  'Origin of the read event: reader, category, competition, etc.';

CREATE INDEX IF NOT EXISTS idx_hadith_progress_hadith_id
  ON public.hadith_progress (hadith_id);
CREATE INDEX IF NOT EXISTS idx_hadith_progress_user_id
  ON public.hadith_progress (user_id);
CREATE INDEX IF NOT EXISTS idx_hadith_progress_user_read_at
  ON public.hadith_progress (user_id, read_at DESC);

ALTER TABLE public.hadith_progress ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "hadith_progress_self_select" ON public.hadith_progress;
CREATE POLICY "hadith_progress_self_select"
  ON public.hadith_progress FOR SELECT
  TO authenticated
  USING (user_id = auth.uid());

DROP POLICY IF EXISTS "hadith_progress_self_insert" ON public.hadith_progress;
CREATE POLICY "hadith_progress_self_insert"
  ON public.hadith_progress FOR INSERT
  TO authenticated
  WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS "hadith_progress_self_delete" ON public.hadith_progress;
CREATE POLICY "hadith_progress_self_delete"
  ON public.hadith_progress FOR DELETE
  TO authenticated
  USING (user_id = auth.uid());

-- No UPDATE policy: a read event is immutable. Re-reads are no-ops via UNIQUE.


-- =============================================================================
-- 3. user_stats
--    Denormalised totals updated by mark_hadith_as_read. Public-readable
--    by authenticated users so leaderboards work.
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.user_stats (
  user_id         uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  hadiths_read    integer NOT NULL DEFAULT 0,
  points          integer NOT NULL DEFAULT 0,
  coins           integer NOT NULL DEFAULT 0,
  trophies        integer NOT NULL DEFAULT 0,
  streak_days     integer NOT NULL DEFAULT 0,
  last_read_date  date,
  level           integer NOT NULL DEFAULT 1,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.user_stats IS
  'Denormalised per-user totals. Updated by mark_hadith_as_read RPC.';

DROP TRIGGER IF EXISTS trg_user_stats_updated_at ON public.user_stats;
CREATE TRIGGER trg_user_stats_updated_at
  BEFORE UPDATE ON public.user_stats
  FOR EACH ROW EXECUTE FUNCTION public.tg_set_updated_at();

ALTER TABLE public.user_stats ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "user_stats_authenticated_read" ON public.user_stats;
CREATE POLICY "user_stats_authenticated_read"
  ON public.user_stats FOR SELECT
  TO authenticated
  USING (true);

DROP POLICY IF EXISTS "user_stats_self_insert" ON public.user_stats;
CREATE POLICY "user_stats_self_insert"
  ON public.user_stats FOR INSERT
  TO authenticated
  WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS "user_stats_self_update" ON public.user_stats;
CREATE POLICY "user_stats_self_update"
  ON public.user_stats FOR UPDATE
  TO authenticated
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS "user_stats_self_delete" ON public.user_stats;
CREATE POLICY "user_stats_self_delete"
  ON public.user_stats FOR DELETE
  TO authenticated
  USING (user_id = auth.uid());


-- =============================================================================
-- 4. achievements
--    Static catalogue of unlockable achievements. Public-readable.
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.achievements (
  id              text PRIMARY KEY,
  name            text NOT NULL,
  description     text NOT NULL,
  icon            text,
  threshold_type  text NOT NULL CHECK (threshold_type IN ('hadiths_read','streak_days','points')),
  threshold_value integer NOT NULL CHECK (threshold_value > 0),
  points_reward   integer NOT NULL DEFAULT 0,
  coins_reward    integer NOT NULL DEFAULT 0,
  sort_order      integer NOT NULL DEFAULT 0,
  created_at      timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.achievements IS
  'Static catalogue. Edit via SQL Editor / migrations only.';

ALTER TABLE public.achievements ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "achievements_public_read" ON public.achievements;
CREATE POLICY "achievements_public_read"
  ON public.achievements FOR SELECT
  TO anon, authenticated
  USING (true);

-- No INSERT/UPDATE/DELETE policies — clients cannot mutate the catalogue.


-- =============================================================================
-- 5. user_achievements
--    Join table. Per-user unlock log. UNIQUE prevents duplicate unlocks.
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.user_achievements (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id         uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  achievement_id  text NOT NULL REFERENCES public.achievements(id) ON DELETE CASCADE,
  unlocked_at     timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT user_achievements_unique UNIQUE (user_id, achievement_id)
);

COMMENT ON TABLE public.user_achievements IS
  'Records which user unlocked which achievement. WRITE-LOCKED to clients: '
  'no INSERT/UPDATE/DELETE policies exist. Rows are inserted ONLY by '
  'public.mark_hadith_as_read (SECURITY DEFINER bypasses RLS). Frontend '
  'must NEVER attempt direct inserts here.';

CREATE INDEX IF NOT EXISTS idx_user_achievements_user_id
  ON public.user_achievements (user_id);

ALTER TABLE public.user_achievements ENABLE ROW LEVEL SECURITY;

-- Defensively drop any insert/delete policies that may exist from prior
-- migration runs. After this migration, only a SELECT policy exists.
DROP POLICY IF EXISTS "user_achievements_self_insert" ON public.user_achievements;
DROP POLICY IF EXISTS "user_achievements_self_delete" ON public.user_achievements;
DROP POLICY IF EXISTS "user_achievements_self_update" ON public.user_achievements;

DROP POLICY IF EXISTS "user_achievements_authenticated_read" ON public.user_achievements;
CREATE POLICY "user_achievements_authenticated_read"
  ON public.user_achievements FOR SELECT
  TO authenticated
  USING (true);

-- Belt-and-suspenders: even without policies, RLS denies writes by default.
-- Explicitly revoking write grants makes the intent unambiguous and
-- prevents an accidentally added policy in the future from silently
-- enabling client writes.
REVOKE INSERT, UPDATE, DELETE ON public.user_achievements FROM anon, authenticated;


-- =============================================================================
-- 6. reading_groups
--    Optional cohorts (e.g., a masjid, a study circle). Public discovery.
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.reading_groups (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  slug        text UNIQUE NOT NULL,
  name        text NOT NULL,
  description text,
  company     text,
  is_public   boolean NOT NULL DEFAULT true,
  created_by  uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now()
);

DROP TRIGGER IF EXISTS trg_reading_groups_updated_at ON public.reading_groups;
CREATE TRIGGER trg_reading_groups_updated_at
  BEFORE UPDATE ON public.reading_groups
  FOR EACH ROW EXECUTE FUNCTION public.tg_set_updated_at();

ALTER TABLE public.reading_groups ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "reading_groups_authenticated_read" ON public.reading_groups;
CREATE POLICY "reading_groups_authenticated_read"
  ON public.reading_groups FOR SELECT
  TO authenticated
  USING (true);

DROP POLICY IF EXISTS "reading_groups_owner_insert" ON public.reading_groups;
CREATE POLICY "reading_groups_owner_insert"
  ON public.reading_groups FOR INSERT
  TO authenticated
  WITH CHECK (created_by = auth.uid());

DROP POLICY IF EXISTS "reading_groups_owner_update" ON public.reading_groups;
CREATE POLICY "reading_groups_owner_update"
  ON public.reading_groups FOR UPDATE
  TO authenticated
  USING (created_by = auth.uid())
  WITH CHECK (created_by = auth.uid());

DROP POLICY IF EXISTS "reading_groups_owner_delete" ON public.reading_groups;
CREATE POLICY "reading_groups_owner_delete"
  ON public.reading_groups FOR DELETE
  TO authenticated
  USING (created_by = auth.uid());


-- =============================================================================
-- 7. reading_group_members
--    Join table user <-> group. Self-managed memberships.
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.reading_group_members (
  group_id   uuid NOT NULL REFERENCES public.reading_groups(id) ON DELETE CASCADE,
  user_id    uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  role       text NOT NULL DEFAULT 'member' CHECK (role IN ('member','admin')),
  joined_at  timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (group_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_reading_group_members_user
  ON public.reading_group_members (user_id);

ALTER TABLE public.reading_group_members ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "reading_group_members_authenticated_read" ON public.reading_group_members;
CREATE POLICY "reading_group_members_authenticated_read"
  ON public.reading_group_members FOR SELECT
  TO authenticated
  USING (true);

DROP POLICY IF EXISTS "reading_group_members_self_join" ON public.reading_group_members;
CREATE POLICY "reading_group_members_self_join"
  ON public.reading_group_members FOR INSERT
  TO authenticated
  WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS "reading_group_members_self_leave" ON public.reading_group_members;
CREATE POLICY "reading_group_members_self_leave"
  ON public.reading_group_members FOR DELETE
  TO authenticated
  USING (user_id = auth.uid());


-- =============================================================================
-- 8. hadith_bookmarks
--    Per-user bookmarks. Migrating from localStorage in the frontend.
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.hadith_bookmarks (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     uuid   NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  hadith_id   bigint NOT NULL,
  created_at  timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT  hadith_bookmarks_user_hadith_unique UNIQUE (user_id, hadith_id)
);

COMMENT ON TABLE public.hadith_bookmarks IS
  'Per-user saved hadiths. hadith_id references public.hadiths.id without FK.';

CREATE INDEX IF NOT EXISTS idx_hadith_bookmarks_user
  ON public.hadith_bookmarks (user_id);
CREATE INDEX IF NOT EXISTS idx_hadith_bookmarks_hadith
  ON public.hadith_bookmarks (hadith_id);

ALTER TABLE public.hadith_bookmarks ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "hadith_bookmarks_self_all" ON public.hadith_bookmarks;
CREATE POLICY "hadith_bookmarks_self_all"
  ON public.hadith_bookmarks FOR ALL
  TO authenticated
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());


-- =============================================================================
-- 9. hadith_notes
--    Per-user free-form notes attached to a hadith.
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.hadith_notes (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     uuid   NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  hadith_id   bigint NOT NULL,
  note        text   NOT NULL CHECK (length(note) BETWEEN 1 AND 8000),
  is_private  boolean NOT NULL DEFAULT true,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.hadith_notes IS
  'Per-user notes per hadith. is_private reserved for future sharing.';

CREATE INDEX IF NOT EXISTS idx_hadith_notes_user
  ON public.hadith_notes (user_id);
CREATE INDEX IF NOT EXISTS idx_hadith_notes_hadith
  ON public.hadith_notes (hadith_id);

DROP TRIGGER IF EXISTS trg_hadith_notes_updated_at ON public.hadith_notes;
CREATE TRIGGER trg_hadith_notes_updated_at
  BEFORE UPDATE ON public.hadith_notes
  FOR EACH ROW EXECUTE FUNCTION public.tg_set_updated_at();

ALTER TABLE public.hadith_notes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "hadith_notes_self_all" ON public.hadith_notes;
CREATE POLICY "hadith_notes_self_all"
  ON public.hadith_notes FOR ALL
  TO authenticated
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());


-- =============================================================================
-- 10. View: user_daily_reading_activity
--     Hadiths read per UTC day per user. Respects RLS via security_invoker.
-- =============================================================================
DROP VIEW IF EXISTS public.user_daily_reading_activity CASCADE;
CREATE VIEW public.user_daily_reading_activity
WITH (security_invoker = on) AS
SELECT
  user_id,
  (read_at AT TIME ZONE 'UTC')::date AS day,
  COUNT(*)::integer                  AS hadiths_read
FROM public.hadith_progress
GROUP BY user_id, (read_at AT TIME ZONE 'UTC')::date;

COMMENT ON VIEW public.user_daily_reading_activity IS
  'Per-user per-day read count. security_invoker=on so RLS limits to own rows.';


-- =============================================================================
-- 11. View: user_collection_progress
--     Per-user per-book completion. Joins hadith_progress with public.hadiths.
-- =============================================================================
DROP VIEW IF EXISTS public.user_collection_progress CASCADE;
CREATE VIEW public.user_collection_progress
WITH (security_invoker = on) AS
WITH book_totals AS (
  SELECT
    book_number,
    COUNT(*)::integer AS total
  FROM public.hadiths
  GROUP BY book_number
)
SELECT
  hp.user_id,
  h.book_number,
  MAX(h.book_name_en)                         AS book_name_en,
  MAX(h.book_name_ar)                         AS book_name_ar,
  COUNT(DISTINCT hp.hadith_id)::integer       AS hadiths_read,
  bt.total                                    AS total_in_book,
  ROUND(
    100.0 * COUNT(DISTINCT hp.hadith_id) / NULLIF(bt.total, 0),
    1
  )::numeric(5,1)                             AS percent_complete
FROM public.hadith_progress hp
JOIN public.hadiths h    ON h.id = hp.hadith_id
JOIN book_totals bt      ON bt.book_number = h.book_number
GROUP BY hp.user_id, h.book_number, bt.total;

COMMENT ON VIEW public.user_collection_progress IS
  'Per-user per-book completion %. security_invoker=on so caller sees own rows only.';


-- =============================================================================
-- 12. View: user_leaderboard
--     Global per-user ranking. All authenticated users see all rows.
-- =============================================================================
DROP VIEW IF EXISTS public.user_leaderboard CASCADE;
CREATE VIEW public.user_leaderboard
WITH (security_invoker = on) AS
SELECT
  ROW_NUMBER() OVER (ORDER BY us.points DESC, us.hadiths_read DESC, us.user_id ASC)::integer
                                                AS rank,
  us.user_id,
  COALESCE(up.display_name, 'Anonymous Reader') AS display_name,
  up.avatar_url,
  up.company,
  us.hadiths_read,
  us.points,
  us.coins,
  us.trophies,
  us.streak_days,
  us.level
FROM public.user_stats us
LEFT JOIN public.user_profiles up ON up.id = us.user_id;

COMMENT ON VIEW public.user_leaderboard IS
  'Global leaderboard. Uses user_stats RLS (authenticated read=true).';


-- =============================================================================
-- 13. View: company_leaderboard
--     Company-level totals derived from user_profiles.company.
-- =============================================================================
DROP VIEW IF EXISTS public.company_leaderboard CASCADE;
CREATE VIEW public.company_leaderboard
WITH (security_invoker = on) AS
SELECT
  ROW_NUMBER() OVER (ORDER BY SUM(us.points) DESC, SUM(us.hadiths_read) DESC, up.company ASC)::integer
                                  AS rank,
  up.company,
  COUNT(DISTINCT us.user_id)::integer AS members,
  SUM(us.hadiths_read)::integer       AS total_hadiths,
  SUM(us.points)::integer             AS total_points,
  SUM(us.trophies)::integer           AS total_trophies
FROM public.user_stats us
JOIN public.user_profiles up ON up.id = us.user_id
WHERE up.company IS NOT NULL AND length(btrim(up.company)) > 0
GROUP BY up.company;

COMMENT ON VIEW public.company_leaderboard IS
  'Company-level aggregates. Companies with empty company field are excluded.';


-- =============================================================================
-- 14. RPC: mark_hadith_as_read
--
--     Single entry point for incrementing user progress. SECURITY DEFINER so
--     it can write user_stats / user_achievements regardless of caller's
--     direct table grants, but it ignores any client-supplied user id and
--     binds strictly to auth.uid().
--
--     Idempotent: calling twice for the same hadith returns already_read=true
--     with no point/coin reward.
--
--     Returns jsonb: {
--       already_read, new_points, new_coins,
--       total_hadiths, total_points, total_coins,
--       streak_days, level, trophies,
--       newly_unlocked: [achievement_id, ...]
--     }
-- =============================================================================
CREATE OR REPLACE FUNCTION public.mark_hadith_as_read(
  p_hadith_id bigint,
  p_source    text DEFAULT 'reader'
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_user            uuid := auth.uid();
  v_role            text := auth.role();
  v_source          text;
  v_already_read    boolean := false;
  v_points_award    integer := 10;
  v_coins_award     integer := 5;
  v_today           date    := (now() AT TIME ZONE 'UTC')::date;
  v_last_date       date;
  v_prev_streak     integer;
  v_streak          integer;
  v_total_hadiths   integer;
  v_total_points    integer;
  v_total_coins     integer;
  v_level           integer;
  v_trophies        integer;
  v_hadith_exists   boolean;
  v_newly_unlocked  text[] := ARRAY[]::text[];
  v_ach             record;
BEGIN
  -- 1. Authenticated? Must satisfy BOTH:
  --    - auth.uid() returns a non-null user id (a real session)
  --    - auth.role() = 'authenticated' (rules out anon and service_role
  --      and prevents service_role from impersonating a user via
  --      manually-set JWT claims)
  IF v_user IS NULL OR v_role IS DISTINCT FROM 'authenticated' THEN
    RAISE EXCEPTION 'unauthorized: must be signed in as an authenticated user'
      USING ERRCODE = '42501';
  END IF;

  -- 2. Normalise the source. Allowlist only — anything unknown collapses
  --    to 'reader'. This keeps the source column reliable for analytics
  --    and prevents arbitrary strings being stored from the frontend.
  v_source := lower(btrim(COALESCE(p_source, 'reader')));
  IF v_source NOT IN ('reader','category','dashboard','competition','import') THEN
    v_source := 'reader';
  END IF;

  -- 3. Hadith exists?
  SELECT EXISTS (
    SELECT 1 FROM public.hadiths WHERE id = p_hadith_id
  ) INTO v_hadith_exists;

  IF NOT v_hadith_exists THEN
    RAISE EXCEPTION 'hadith % not found', p_hadith_id
      USING ERRCODE = 'P0002';
  END IF;

  -- 4. Lazy-create profile + stats rows.
  INSERT INTO public.user_profiles (id)
    VALUES (v_user)
    ON CONFLICT (id) DO NOTHING;

  INSERT INTO public.user_stats (user_id)
    VALUES (v_user)
    ON CONFLICT (user_id) DO NOTHING;

  -- 5. Insert progress; tell us whether it was a new read.
  WITH ins AS (
    INSERT INTO public.hadith_progress (user_id, hadith_id, source)
    VALUES (v_user, p_hadith_id, v_source)
    ON CONFLICT (user_id, hadith_id) DO NOTHING
    RETURNING 1
  )
  SELECT NOT EXISTS (SELECT 1 FROM ins) INTO v_already_read;

  -- 6. Idempotent path: already read → return current totals, no reward.
  IF v_already_read THEN
    SELECT hadiths_read, points, coins, trophies, streak_days, level
      INTO v_total_hadiths, v_total_points, v_total_coins,
           v_trophies, v_streak, v_level
      FROM public.user_stats
      WHERE user_id = v_user;

    RETURN jsonb_build_object(
      'already_read',   true,
      'new_points',     0,
      'new_coins',      0,
      'total_hadiths',  COALESCE(v_total_hadiths, 0),
      'total_points',   COALESCE(v_total_points, 0),
      'total_coins',    COALESCE(v_total_coins, 0),
      'streak_days',    COALESCE(v_streak, 0),
      'level',          COALESCE(v_level, 1),
      'trophies',       COALESCE(v_trophies, 0),
      'newly_unlocked', '[]'::jsonb
    );
  END IF;

  -- 7. New read — compute streak.
  SELECT last_read_date, streak_days
    INTO v_last_date, v_prev_streak
    FROM public.user_stats
    WHERE user_id = v_user;

  IF v_last_date IS NULL THEN
    v_streak := 1;
  ELSIF v_last_date = v_today THEN
    v_streak := COALESCE(v_prev_streak, 1);
  ELSIF v_last_date = (v_today - INTERVAL '1 day')::date THEN
    v_streak := COALESCE(v_prev_streak, 0) + 1;
  ELSE
    v_streak := 1;
  END IF;

  -- 8. Apply totals.
  UPDATE public.user_stats
     SET hadiths_read   = hadiths_read + 1,
         points         = points + v_points_award,
         coins          = coins  + v_coins_award,
         streak_days    = v_streak,
         last_read_date = v_today,
         level          = 1 + ((points + v_points_award) / 100),
         updated_at     = now()
   WHERE user_id = v_user
   RETURNING hadiths_read, points, coins, level
        INTO v_total_hadiths, v_total_points, v_total_coins, v_level;

  -- 9. Unlock any achievements whose threshold is now met.
  --    NOTE: clients cannot insert into user_achievements directly.
  --    This is the only code path that writes to that table.
  FOR v_ach IN
    SELECT a.id
      FROM public.achievements a
     WHERE NOT EXISTS (
             SELECT 1
               FROM public.user_achievements ua
              WHERE ua.user_id        = v_user
                AND ua.achievement_id = a.id
           )
       AND (
             (a.threshold_type = 'hadiths_read' AND v_total_hadiths >= a.threshold_value) OR
             (a.threshold_type = 'streak_days'  AND v_streak        >= a.threshold_value) OR
             (a.threshold_type = 'points'       AND v_total_points  >= a.threshold_value)
           )
  LOOP
    INSERT INTO public.user_achievements (user_id, achievement_id)
    VALUES (v_user, v_ach.id)
    ON CONFLICT (user_id, achievement_id) DO NOTHING;
    v_newly_unlocked := array_append(v_newly_unlocked, v_ach.id);
  END LOOP;

  -- 10. Update trophies count from the join table.
  SELECT COUNT(*)::integer
    INTO v_trophies
    FROM public.user_achievements
    WHERE user_id = v_user;

  UPDATE public.user_stats
     SET trophies = v_trophies,
         updated_at = now()
   WHERE user_id = v_user;

  -- 11. Return summary.
  RETURN jsonb_build_object(
    'already_read',   false,
    'new_points',     v_points_award,
    'new_coins',      v_coins_award,
    'total_hadiths',  v_total_hadiths,
    'total_points',   v_total_points,
    'total_coins',    v_total_coins,
    'streak_days',    v_streak,
    'level',          v_level,
    'trophies',       v_trophies,
    'newly_unlocked', to_jsonb(v_newly_unlocked)
  );
END;
$$;

COMMENT ON FUNCTION public.mark_hadith_as_read(bigint, text) IS
  'Idempotent mark-as-read. SECURITY DEFINER, search_path = public, pg_temp. '
  'Auth gate requires both auth.uid() IS NOT NULL and auth.role() = '
  '''authenticated''. Does not accept p_user_id; binds strictly to auth.uid(). '
  'Normalises p_source to one of: reader, category, dashboard, competition, '
  'import (anything else collapses to ''reader''). Sole writer to '
  'public.user_achievements — clients cannot insert there directly.';

-- Grants: only authenticated callers may invoke. Anon must sign in first.
REVOKE ALL ON FUNCTION public.mark_hadith_as_read(bigint, text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.mark_hadith_as_read(bigint, text) FROM anon;
GRANT EXECUTE ON FUNCTION public.mark_hadith_as_read(bigint, text) TO authenticated;


-- =============================================================================
-- 15. Achievements seed (idempotent)
-- =============================================================================
INSERT INTO public.achievements
  (id, name, description, icon, threshold_type, threshold_value, points_reward, coins_reward, sort_order)
VALUES
  ('first_step',         'First Step',           'Read your first hadith',                 'badge-first',     'hadiths_read',  1,    10,    5,   10),
  ('ten_hadith',         'Ten Hadith',           'Read 10 hadiths',                        'badge-ten',       'hadiths_read',  10,   50,    25,  20),
  ('fifty_hadith',       'Fifty Hadith',         'Read 50 hadiths',                        'badge-fifty',     'hadiths_read',  50,   200,   100, 30),
  ('hundred_hadith',     'One Hundred Hadith',   'Read 100 hadiths',                       'badge-hundred',   'hadiths_read',  100,  500,   250, 40),
  ('five_hundred_hadith','Devoted Reader',       'Read 500 hadiths',                       'badge-fivehundred','hadiths_read', 500,  2000,  1000,50),
  ('thousand_hadith',    'One Thousand Hadith',  'Read 1,000 hadiths',                     'badge-thousand',  'hadiths_read',  1000, 5000,  2500,60),
  ('three_day_streak',   'Three-Day Streak',     'Read on three consecutive days',         'badge-streak3',   'streak_days',   3,    30,    15,  70),
  ('seven_day_streak',   'Seven-Day Streak',     'Read on seven consecutive days',         'badge-streak7',   'streak_days',   7,    100,   50,  80),
  ('thirty_day_streak',  'Thirty-Day Streak',    'Read on thirty consecutive days',        'badge-streak30',  'streak_days',   30,   500,   250, 90)
ON CONFLICT (id) DO NOTHING;


-- =============================================================================
-- 16. View grants
-- =============================================================================
GRANT SELECT ON public.user_daily_reading_activity TO authenticated;
GRANT SELECT ON public.user_collection_progress    TO authenticated;
GRANT SELECT ON public.user_leaderboard            TO authenticated;
GRANT SELECT ON public.company_leaderboard         TO authenticated;


COMMIT;

-- =============================================================================
-- END OF MIGRATION 001
-- =============================================================================
